stages:
  - test
  - validate

run:
  stage: test
  image: golang
  script:
    - go build
    - go test
  artifacts:
    paths:
      - fakeresults.xml
    expire_in: 14 mins

xsd:
  stage: validate
  image: ubuntu
  before_script:
    - apt install -y --no-install-recommends libxml2-utils
  script:
    - xmllint --noout --schema junit-10.xsd fakeresults.xml
