stages:
  - test
  - validate

run:
  stage: test
  image: golang
  script:
    - go build
    - go test
  artifacts:
    paths:
      - fakeresults.xml
    expire_in: 14 mins

xsd:
  stage: validate
  image: ubuntu
  before_script:
    - apt install xmlstarlet
  script:
    - xmlstarlet val -e -s junit-10.xsd fakeresults.xml
